import 'dart:async';
import 'dart:convert';
import 'dart:math' as math;
import 'package:barcode_widget/barcode_widget.dart' as bw;
import 'package:image/image.dart' as img;
import 'package:screen_brightness/screen_brightness.dart';
import 'package:zxing2/qrcode.dart'
    show
        BinaryBitmap,
        GlobalHistogramBinarizer,
        QRCodeReader,
        RGBLuminanceSource;

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' as foundation;
import 'package:flutter/services.dart';
import 'package:emoji_picker_flutter/emoji_picker_flutter.dart' as ep;
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:image_picker/image_picker.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:crypto/crypto.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_timezone/flutter_timezone.dart';
import 'package:timezone/timezone.dart' as tz;
import 'package:timezone/data/latest.dart' as tz;

part 'src/app/app.dart';
part 'src/shared/theme.dart';
part 'src/shared/icons.dart';
part 'src/shared/analytics.dart';
part 'src/shared/utils.dart';
part 'src/shared/notifications_service.dart';
part 'src/shared/device_calendar_sync.dart';
part 'src/features/budget/models/budget_models.dart';
part 'src/features/lists/models/list_models.dart';
part 'src/features/calendar/models/calendar_models.dart';
part 'src/features/calendar/data/ics_import.dart';
part 'src/features/weekly/models/weekly_plan_models.dart';
part 'src/features/wallet/models/wallet_models.dart';
part 'src/features/wallet/data/card_import.dart';
part 'src/features/wallet/presentation/wallet_screens.dart';
part 'src/features/wallet/presentation/wallet_sheets.dart';
part 'src/features/account/models/account_models.dart';
part 'src/features/account/data/family_cloud.dart';
part 'src/features/account/data/workspace_sections.dart';
part 'src/features/budget/presentation/thrive_home.dart';
part 'src/features/navigation/presentation/app_shell.dart';
part 'src/features/navigation/presentation/placeholder_screens.dart';
part 'src/features/navigation/presentation/quickadd_sheets.dart';
part 'src/features/lists/presentation/list_actions.dart';
part 'src/features/lists/presentation/list_screens.dart';
part 'src/features/lists/presentation/list_sheets.dart';
part 'src/features/calendar/presentation/calendar_actions.dart';
part 'src/features/calendar/presentation/calendar_screens.dart';
part 'src/features/calendar/presentation/calendar_sheets.dart';
part 'src/features/calendar/presentation/kitchen_dashboard_screen.dart';
part 'src/features/weekly/presentation/weekly_plan_actions.dart';
part 'src/features/weekly/presentation/weekly_plan_screen.dart';
part 'src/features/weekly/presentation/weekly_plan_sheets.dart';
part 'src/features/home/models/home_board_models.dart';
part 'src/features/home/presentation/home_screen.dart';
part 'src/features/home/presentation/home_board.dart';
part 'src/features/home/presentation/home_board_widgets.dart';
part 'src/features/home/presentation/home_board_sheets.dart';
part 'src/features/budget/presentation/thrive_screens.dart';
part 'src/features/budget/presentation/thrive_flow.dart';
part 'src/features/budget/presentation/thrive_stats.dart';
part 'src/features/budget/presentation/thrive_widgets.dart';
part 'src/features/budget/presentation/thrive_sheets.dart';
part 'src/features/account/presentation/account_actions.dart';
part 'src/features/account/presentation/auth_screen.dart';
part 'src/features/account/presentation/onboarding_screen.dart';
part 'src/features/account/presentation/account_sheets.dart';
part 'src/features/navigation/presentation/more_screen.dart';
